### ISSUE TITLE
how to use the CHIP-Human or CHIP-Human-ids to train semantic segmentation？

### ISSUE THREAD

**Issue by zhangyunming** [Engineering-Course/CIHP_PGN#12]
hi，thanks for sharing the CHIP datasets, its a perfect dataset i have seen for human.
currently，i want to use the data to train semantic segmentation,but the chip human or chip-human-ids has many colors, one color respect a class, and i am not clear the class numbers.  so can you give the number of color in chip-trainning-human  an every color-value，thank you。

i have  idea , can i use opencv  to transfor the pixel in chip-hunman  images to 255 or some value >0 if the value !=0?
so the image only have 000 for background and 255,255,255 for human?

Looking forward to your feedback，thanks again.

**Comment by Engineering-Course** [comment]
CIHP-human is for visualization.  CIHP-human-ids is the label for training.  The pixel value in human-ids is from 0 to 19, which is defined [here](http://sysu-hcp.net/lip/mparsing_challenge.php). 
You can use human-ids to train semantic segmentation.

**Comment by zhangyunming** [comment]
thank you for your reply!

YES,the human-ids image is 8bit,can train semantic segmentation,but the class(color) is 19+1. i want to change the class to 2. so can i change the human images to black and one anathor color ,later change the human images to 8bit ids?

one more question：
in https://github.com/GeorgeSeif/Semantic-Segmentation-Suite 
the train datasets need 24 images label and its color value of rgb, so how can i use the CHIP to train person seg?

**Comment by Engineering-Course** [comment]
Yes. You can change the class to 2 and use CIHP to train person segmentation.

**Comment by rishab-sharma** [comment]
@Engineering-Course In the case of training for semantic segmentation, will I be able to use the pre-trained weights provided by the repo?
