### ISSUE TITLE
Error:undefined name 'basestring'

### ISSUE THREAD

**Issue by pnzsl** [Engineering-Course/CIHP_PGN#13]
Hello! I was lucky to see this article in the news, and I found the source program here. I'm sorry to disturb you. Now there are some problems in debugging the running program. Have you ever had such a problem? If so, how should we solve this problem? Do you mind solving it for me? Thank you.

The problem is that

  File "C:\Users\Administrator\Desktop\CIHP_PGN-master\kaffe\tensorflow\network.py", line 78, in feed
    if isinstance(fed_layer,basestring):

NameError: name 'basestring' is not defined.

**Comment by Engineering-Course** [comment]
change `basestring` to `str`

**Comment by pnzsl** [comment]
> 
> 
> change `basestring` to `str`
The problem have been solved.thank you!
