### ISSUE TITLE
How to get the txt files and the groundtruth of the test dataset?

### ISSUE THREAD

**Issue by wuxifang1994** [Engineering-Course/CIHP_PGN#14]
Thank you for your great work. I wonder how to get the txt files like the txt files in the evaluation/Instance_part_val? And where is the groundtruth of  the test dataset?

**Comment by Engineering-Course** [comment]
The ground truth of the test set is withheld for benchmarking purposes. You can refer to [our dataset website](http://sysu-hcp.net/lip/mparsing_challenge.php) for more details of the txt format.
