### ISSUE TITLE
purpose of tail_list_rev in test_pgn.py?

### ISSUE THREAD

**Issue by peterson123** [Engineering-Course/CIHP_PGN#15]
Hi, can anyone explain this code in test_pgn.py? I'm really confused. Why choose the order of output channel 14-19, and reverse them?

   for xx in xrange(14):
        tail_list_rev[xx] = tail_list[xx]
    tail_list_rev[14] = tail_list[15]
    tail_list_rev[15] = tail_list[14]
    tail_list_rev[16] = tail_list[17]
    tail_list_rev[17] = tail_list[16]
    tail_list_rev[18] = tail_list[19]
    tail_list_rev[19] = tail_list[18]
    tail_output_rev = tf.stack(tail_list_rev, axis=2)
    tail_output_rev = tf.reverse(tail_output_rev, tf.stack([1]))

Thanks

**Comment by Engineering-Course** [comment]
They are left and right labels (e.g. left-arm and right-arm) that cannot be simply handled by flip function.
