### ISSUE TITLE
The code is voilated with the paper

### ISSUE THREAD

**Issue by pkuCactus** [Engineering-Course/CIHP_PGN#16]
In your [code](https://github.com/Engineering-Course/CIHP_PGN/blob/master/utils/model_pgn.py#L500) , your refine feat combine feat after PPM and remap feat, while in your paper you combine the feat before PPM and remap feat. Which is the really feat you use？

**Comment by Engineering-Course** [comment]
remap, combine, ppm. I think the code is consistent with the paper.

**Comment by pkuCactus** [comment]
![image](https://user-images.githubusercontent.com/30314249/48688820-b5dc3f00-ec02-11e8-8d65-8f0dcd818a59.png)
 (self.feed('parsing_branch', 'parsing_pp1', 'parsing_pp2', 'parsing_pp3', 'parsing_pp4')
             .concat(axis=3, name='parsing_pp_out')
             .conv(3, 3, 512, 1, 1, biased=True, relu=True, name='parsing_pp_conv')
 (self.feed('parsing_pp_conv')
             .conv(3, 3, 256, 1, 1, biased=True, relu=True, name='parsing_fea'))
        (self.feed('parsing_fc')

**Comment by Engineering-Course** [comment]
![image](https://user-images.githubusercontent.com/7713394/48689193-4cf5c680-ec04-11e8-8687-e52917dd47ca.png)
If you are talking about this combination, the code is from line 501 to 512.

**Comment by pkuCactus** [comment]
I know the code is from line 501 to 512, what  i mean is the feat which to get from. In your paper you take the feat before PPM while in code you take from the feat after the PPM.

**Comment by Engineering-Course** [comment]
Oh, I see!
Sorry, our figure is not very clear.  You can refer to the code for the implementation. 
Thanks.

**Comment by pkuCactus** [comment]
ok, thanks for your reply.
