### ISSUE TITLE
INST_PART_GT_DIR = './Instance_part_val'

### ISSUE THREAD

**Issue by zicair** [Engineering-Course/CIHP_PGN#18]
Hello, thanks for the code .

First: I have a question that how do you get the data in the "Instance_part_val" directory? In code, you use 
both the data in that directory and cihp_instance_part_maps to valuate scripts which in $HOME/evaluation.

Second: I would like to train the model in Pascal, but Pascal does not have labels like in CIHP. How do you  
run train_pgn.py to train PGN.model in PASCAL  Dataset ?

Thank you and look forward to your reply!

**Comment by Engineering-Course** [comment]
The data of _Instance_part_val_ are used for facilitating the evaluation, which is generated from the annotation.
You can find instance-level labels of Pascal [here](http://www.stat.ucla.edu/~xianjie.chen/pascal_part_dataset/pascal_part.html#statistics)
