### ISSUE TITLE
Some question?

### ISSUE THREAD

**Issue by ChenDRAG** [Engineering-Course/CIHP_PGN#19]
Is there a test file for us just to get the results of our own data, without having to have the groundtruth?

**Comment by ChenDRAG** [comment]
Also, could you please give me a specific meaning for each label? Currently I cannot find one and only get this in your code.
n_classes = 20
```
# colour map
label_colours = [(0,0,0)
                , (128,0,0), (255,0,0), (0,85,0), (170,0,51), (255,85,0), (0,0,85), (0,119,221), (85,85,0), (0,85,85), (85,51,0), (52,86,128), (0,128,0)
                , (0,0,255), (51,170,221), (0,255,255), (85,255,170), (170,255,85), (255,255,0), (255,170,0)]

# label_colours = [(0,0,0)
#                 # 0=background
#                 ,(128,0,0), (0,128,0), (128,128,0), (0,0,128), (128,0,128), (0,128,128)]
#                 # 1=head, 2=torso, 3=upper arm, 4=lower arm, 5=upper leg, # 6=lower leg
# image mean
```

**Comment by Engineering-Course** [comment]
The predicted results can be saved and you can comment the code for evaluation in test_pgn.py
The labels for 20 classes are
Background
Hat
Hair
Glove
Sunglasses
Upper-clothes
Dress
Coat
Socks
Pants
tosor-skin
Scarf
Skirt
Face
Left-arm
Right-arm
Left-leg
Right-leg
Left-shoe
Right-shoe

**Comment by ChenDRAG** [comment]
Got it，thanks！
