### ISSUE TITLE
how to get the pngs in "datasets/CHIP/labels"

### ISSUE THREAD

**Issue by rudy-letote** [Engineering-Course/CIHP_PGN#21]
Thank you for your great work. I wonder how to get the pngs in datasets/CHIP/labels of my own pic.look forward to your message

**Comment by rudy-letote** [comment]
and datasets/CHIP/enges?  look forward to your message，thanks very much .

**Comment by Engineering-Course** [comment]
@rudy-letote Sorry. I don't understand your need. How to inference using your own pic is written in Readme

**Comment by rudy-letote** [comment]
how to get pictures which exists in  datasets/CHIP/enges?

**Comment by rudy-letote** [comment]
> how to get pictures which exists in datasets/CHIP/enges?

i want to predict mine  pictures which i store in datasets/CIHP/images/，but how can i get pictures which should exist in datasets/CHIP/enges?

**Comment by Engineering-Course** [comment]
You don't need it.  Or put any png in edges/

**Comment by neonb88** [comment]
> You don't need it. Or put any png in edges/

@Engineering-Course does the png have to have the same dimensions as your image?
