### ISSUE TITLE
what the environment or requirement for this project？

### ISSUE THREAD

**Issue by MISSXUAN0** [Engineering-Course/CIHP_PGN#28]
When i running this project，I have encountered a segmentation Fault(core dump).So I guess there is a problem with my environment.
My environment as follows：
systerm：Ubuntu14.04
cuda：9.0
tensorflow：1.11.0
Is there any problem with my environment? Can you provide the version requirements you use？

**Comment by MISSXUAN0** [comment]
I can run it after change tensorflow version as 1.9.0 and python version as 2.7

**Comment by MuhammadAsadJaved** [comment]
> I can run it after change tensorflow version as 1.9.0 and python version as 2.7

Hi, Are you using Tensorflow CPU or tensorflow-gpu ?
