### ISSUE TITLE
OS influence with the code (Windows/Ubuntu)

### ISSUE THREAD

**Issue by AIdeveloper-oz** [Engineering-Course/CIHP_PGN#43]
Hi, thanks for sharing your work. I have executed this project, in my machine with Windows 10 OS. It fails to execute when the cuda capable gpu is pointed. But runs without any issues if the cpu is pointed. 

When it comes to Ubuntu18.04.4 LTS , I got stuck with the Segmentation Fault Core Dumped error. I have installed all necessary packages. Help me clear this error and run in UBUNTU. 
Thanks in advance.

**Comment by neonb88** [comment]
Let us know what progress you've made tomorrow.  Probably won't be able to help with 18.04, sry

**Comment by AIdeveloper-oz** [comment]
Hi neonb88 thanks for your reply. I have been working on this for a while. As I stated earlier, the same code works fine with Windows 10. I tested in google Colab and it worked even there. If its's required to  downgrade the Ubuntu version, i shall give it a try.

**Comment by AIdeveloper-oz** [comment]
Thanks Nathan I cleared the issue.

**Comment by amrahsmaytas** [comment]
> Hi neonb88 thanks for your reply. I have been working on this for a while. As I stated earlier, the same code works fine with Windows 10. I tested in google Colab and it worked even there. If its's required to downgrade the Ubuntu version, i shall give it a try.

HI @AIdeveloper-oz , could you please be kind enough to share the google colab implementation of the  cihp_pgn , awaiting  for your kind response.

Thanks,
satyam sharma.
