### ISSUE TITLE
Model converted to onnx

### ISSUE THREAD

**Issue by ykk648** [Engineering-Course/CIHP_PGN#74]
[ykk648/AI_power@main/seg_lib/cihp_pgn/cihp_pgn_api.py](https://github.com/ykk648/AI_power/blob/main/seg_lib/cihp_pgn/cihp_pgn_api.py)
I converted pgn model to onnx from tf1.5 (tf2pb2onnx), mind that image size will increase GPU mem significantly.
There are some errors when running shape-infer to onnx model, so this model can not use tensorrt mode(fp16) for now.
 
#72 #42 #71 #70 #44 #46

**Comment by ykk648** [comment]
issue close

**Comment by Mahmoud-SaadEl-Din** [comment]
could you please provide onnx conversion code?

**Comment by ykk648** [comment]
Sorry, it's been too long, I didn't save the code back then 

> could you please provide onnx conversion code?
