### ISSUE TITLE
Instance partition process

### ISSUE THREAD

**Issue by mabravo641** [Engineering-Course/CIHP_PGN#8]
Hi,
I have downloaded your code and read it carefully. I really enjoy and admire your work. The only thing was that I couldn’t find the Instance partition process that you talk in the paper. Could you tell me in which of the scripts, and in what part, you do the Instance partition process?

Thank you

**Comment by hanqing1** [comment]
Thank you for your work, could you tell me that whether the color map of instance-level human parsing is unique or not, and must keep the same as the instance Ground Truth?
