### ISSUE TITLE
How to predict for just one image ?

### ISSUE THREAD

**Issue by kaanakan** [Engineering-Course/CIHP_PGN#9]
Hi,
I am trying to see the result of a in-the-wild image, but seemingly there is no setting for that. 
Is there any script which receives a image and outputs edge mask? I tried test_pgn.py but I think it is not for single image prediction.

Thanks in advance...

**Comment by Engineering-Course** [comment]
To predict one image, you should first create a txt with the image name in it and then you can use test_pgn.py.
